# Generated by Django 5.0.4 on 2024-04-19 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menuitem_category_menuitem_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTypeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(blank=True, choices=[('round', 'Round'), ('square', 'Square')], default='square', max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='discount',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='card_type_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cardtypesetting'),
        ),
    ]
