# Generated by Django 5.0.4 on 2024-04-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_remove_menuitem_card_type_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='card_type',
            field=models.CharField(choices=[('round', 'Round'), ('square', 'Square')], default='square', max_length=10),
        ),
    ]
