# Generated by Django 5.0.4 on 2024-04-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_menuitem_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='card_type_setting',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
