# Generated by Django 5.0.4 on 2024-04-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_menuitem_card_type_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='card_type_setting',
            new_name='cooking_duration',
        ),
    ]
