# Generated by Django 5.0.4 on 2024-04-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_card_type_setting_menuitem_cooking_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardTypeSetting',
        ),
    ]
