# Generated by Django 5.0.4 on 2024-04-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_cardtypesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
