# Generated by Django 5.0.4 on 2026-09-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('served', 'Served')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
